---
- name: install dependencies
  apt: name={{item}} state=present
  with_items:
    - libssh2-php

- name: Download and extract WordPress
  unarchive: src=http://wordpress.org/wordpress-{{ wp_version }}.tar.gz dest=/var/www/ copy=no

- name: Fetch random salts for WordPress config
  local_action: command curl https://api.wordpress.org/secret-key/1.1/salt/
  register: "wp_salt"
  sudo: no

- name: Create WordPress database
  mysql_db: name={{ wp_db_name }} state=present login_password={{ mysql_root_passwd }}

- name: Create WordPress database user
  mysql_user: name={{ wp_db_user }} password={{ wp_db_password }} priv={{ wp_db_name }}.*:ALL host='localhost' state=present login_password={{ mysql_root_passwd }}

- name: Copy WordPress config file
  template: src=wp-config.php dest=/var/www/wordpress/

- name: Create the uploads directory
  file: path=/var/www/wordpress/wp-content/uploads state=directory owner=www-data

- name: Change ownership of WordPress installation
  file: path=/var/www/wordpress/ owner=www-data group=www-data state=directory recurse=yes

- name: Change defaut config
  lineinfile: dest=/etc/nginx/sites-available/default regexp="{{item.regexp}}" line="{{item.line}}"
  with_items:
    - { regexp: '^\troot /var/www/html;', line: "\troot /var/www/wordpress;"}
    - { regexp: '^\tindex index.html index.htm;', line: "\tindex index.php index.html index.htm;"}
    - { regexp: '^\t\ttry_files \$uri \$uri/ =404;', line: "\t\ttry_files $uri $uri/ /index.php?q=$uri&$args;"}

- name: Restart Nginx
  service: name=nginx state=restarted

- name: Start php-fpm Service
  service: name=php5-fpm state=started enabled=yes
