---
- name: install php5 and related libs
  apt: name={{item}} state=present
  with_items:
    - php5-fpm
    - php5-mysql
    - php5-gd
    - php5-curl

- name: secure php config
  lineinfile: dest=/etc/php5/fpm/php.ini regexp="{{item.regexp}}" line="{{item.line}}"
  with_items:
    - { regexp: '^;cgi.fix_pathinfo', line: 'cgi.fix_pathinfo=0'}
    - { regexp: '^upload_max_filesize', line: 'upload_max_filesize = {{php_upload_max_filesize}}'}
    - { regexp: '^post_max_size', line: 'post_max_size = {{php_post_max_size}}'}

- name: Copy nginx configuration for wordpress
  template: src=default dest=/etc/nginx/sites-available/default

- name: Restart Nginx
  service: name=nginx state=restarted
